### ISSUE TITLE
Manage external Storage

### ISSUE THREAD

**Issue by nikulvaghasiya** [GauthamAsir/WhatsApp_Status_Saver#11]
[WhatsApp StatusSaver](https://play.google.com/store/apps/details?id=com.videoplayerhd.allvideoplayerformate&hl=en)

https://play.google.com/store/apps/details?id=com.videoplayerhd.allvideoplayerformate&hl=en

this app working fine without manage external storage permission and target sdk version =>30

**Comment by GauthamAsir** [comment]
No comments...
