### ISSUE TITLE
Access folder

### ISSUE THREAD

**Issue by sushantj651** [GauthamAsir/WhatsApp_Status_Saver#2]
How we can access .statuses folder if Environment.getExternalStorageDirectory() removed in android 11?

**Comment by fuchsialab** [comment]
same problem

**Comment by GauthamAsir** [comment]
Refer Scoped Storage Framework (SAF).

**Comment by sushantj651** [comment]
Where will be the .statuses folder in Android 11?

**Comment by GauthamAsir** [comment]
> Where will be the .statuses folder in Android 11?

Same Location .../WhatsApp/.Statuses

**Comment by sushantj651** [comment]
Can we create folder in outside the Android folder in Android 11?

**Comment by GauthamAsir** [comment]
> Can we create folder in outside the Android folder in Android 11?

Yes you can, using SAF.

**Comment by GauthamAsir** [comment]
Will push an update for Android 11.
