### ISSUE TITLE
no files found 

### ISSUE THREAD

**Issue by Alanqiu** [GauthamAsir/WhatsApp_Status_Saver#4]
images ， videos Cant find WhatsApp Dir , saved files no files found

**Comment by Alanqiu** [comment]
![image](https://user-images.githubusercontent.com/5857925/120735944-05af5700-c51e-11eb-8aa9-7f07804f97fb.png)
With this permission, will GooglePlay refuse to pass?

**Comment by GauthamAsir** [comment]
> images ， videos Cant find WhatsApp Dir , saved files no files found

Its Fixed Now.
